// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20181208041910_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("TodoApi.Models.DayLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<long>("TodoLogId");

                    b.Property<bool>("isComplete");

                    b.HasKey("Id");

                    b.HasIndex("TodoLogId");

                    b.ToTable("DayLog");
                });

            modelBuilder.Entity("TodoApi.Models.TargetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HealthState");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("TargetItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Time");

                    b.Property<long>("TodoLogForeignKey");

                    b.HasKey("Id");

                    b.HasIndex("TodoLogForeignKey")
                        .IsUnique();

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("TargetItemId");

                    b.HasKey("Id");

                    b.HasIndex("TargetItemId");

                    b.ToTable("TodoLogs");
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Birth");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoApi.Models.DayLog", b =>
                {
                    b.HasOne("TodoApi.Models.TodoLog", "TodoLog")
                        .WithMany("DayLogs")
                        .HasForeignKey("TodoLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.HasOne("TodoApi.Models.TodoLog", "TodoLog")
                        .WithOne("TodoItem")
                        .HasForeignKey("TodoApi.Models.TodoItem", "TodoLogForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TodoApi.Models.TodoLog", b =>
                {
                    b.HasOne("TodoApi.Models.TargetItem", "TargetItem")
                        .WithMany("Logs")
                        .HasForeignKey("TargetItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
