// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20181217055459_version13")]
    partial class version13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TodoApi.Models.DayLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<long>("TodoLogId");

                    b.Property<bool>("isComplete");

                    b.HasKey("Id");

                    b.HasIndex("TodoLogId");

                    b.ToTable("DayLogs");
                });

            modelBuilder.Entity("TodoApi.Models.TargetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HealthState");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("TargetItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsBuildIn");

                    b.Property<int?>("Mode");

                    b.Property<string>("ModeValue");

                    b.Property<string>("Name");

                    b.Property<int>("Time");

                    b.Property<int>("TimesForMode");

                    b.Property<int?>("Type");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("TargetItemId");

                    b.Property<long>("TodoItemId");

                    b.HasKey("Id");

                    b.HasIndex("TargetItemId");

                    b.HasIndex("TodoItemId");

                    b.ToTable("TodoLogs");
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Birth");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoApi.Models.DayLog", b =>
                {
                    b.HasOne("TodoApi.Models.TodoLog", "TodoLog")
                        .WithMany("DayLogs")
                        .HasForeignKey("TodoLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TodoApi.Models.TodoLog", b =>
                {
                    b.HasOne("TodoApi.Models.TargetItem", "TargetItem")
                        .WithMany("Logs")
                        .HasForeignKey("TargetItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TodoApi.Models.TodoItem", "TodoItem")
                        .WithMany("Logs")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
